### ISSUE TITLE
Integrating {php}IPAM with vRealize Automation 8 - Virtually Potato

### ISSUE THREAD

**Issue by utterances-bot** [vimwtf/site-comments#15]
# Integrating {php}IPAM with vRealize Automation 8 - Virtually Potato

In a previous post, I described some of the steps I took to stand up a homelab including vRealize Automation (vRA) on an Intel NUC 9. One of my initial goals for that lab was to use it for developing and testing a way for vRA to leverage phpIPAM for static IP assignments. The homelab worked brilliantly for that purpose, and those extra internal networks were a big help when it came to testing. I was able to deploy and configure a new VM to host the phpIPAM instance, install the VMware vRealize Third-Party IPAM SDK on my Chromebook’s Linux environment, develop and build the integration component, import it to my vRA environment, and verify that deployments got addressed accordingly.

[https://virtuallypotato.com/integrating-phpipam-with-vrealize-automation-8](https://virtuallypotato.com/integrating-phpipam-with-vrealize-automation-8)

**Comment by kuklis** [comment]
Hi John,
have you tested the plugin with vRA 8.6 yet? I've also developed the same plugin last year and used the owner field to register the requestor in phpIPAM record, just like you did.
Now my plugin started to fail and I noticed the owner property is no longer in the ABX input payload, causing an error.

**Comment by vimwtf** [comment]
Hi @kuklis!

I did indeed encounter the [same issue](https://github.com/jbowdre/phpIPAM-for-vRA8/issues/2), and reached the same conclusion as you: it looks like vRA 8.6 broke the IPAM SDK contract and is no longer providing the `owner` property to IPAM integrations.

I worked around this by [removing the reference to that property](https://github.com/jbowdre/phpIPAM-for-vRA8/commit/21ed9d7c668b83e1385a5d9f91d2a002b3e2ffa7) in my code and building a [new release version](https://github.com/jbowdre/phpIPAM-for-vRA8/releases/tag/v1.0.4). 

I also opened a case with VMware support who confirmed that it's a bug, and they've opened an internal PR to get it corrected "soon". Given the rapid release cadence they've adopted lately, (1) I'm not surprised and (2) I suspect we'll just see it fixed in 8.7 rather than getting a mid-cycle hotfix. 

I hope to be able to revert this and easily capture ownership information in my IPAM solution again soon, but for now at least my deployments are working again.

Cheers,
John

**Comment by kuklis** [comment]
Thanks for checking. We do have a custom field with owner information, I'll use that instead until the bug is fixed.

**Comment by musclar92** [comment]
Hello John!
I tried integrate my vra 8.2 with phpIPAM 1.3 and unfortunately it doesn't work. After validation step I got error that IPAM provider not found.   
"Failed to validate credentials. AdapterReference: http://provisioning-service.prelude.svc.cluster.local:8282/provisioning/adapter/ipam/endpoint-config. Error: IPAM Provider 'eaa2b2b0-a497-47d9-8069-e9e0ab8895d5' not found. "

Maybe you have any idea where i should look for error?

**Comment by vimwtf** [comment]
Hi @musclar92,

That's a strange error. Maybe try clicking **Manage IPAM Providers** and then importing the provider package again to see if that makes a difference? I'd also look at **Cloud Assembly > Extensibility > Activity > Action Runs** and flip the toggle near the top of the screen from *User Runs* to *Integration Runs*. That should let you view some more details about the failed validation run which may shed more light on the issue. 

Good luck!

**Comment by musclar92** [comment]
Unfortunately import the provider package again not make any deiference. I checked Action Runs, and see new error: 

 [37mDEBU[0m[0000] Copying file /workspace/Dockerfile to /kaniko/Dockerfile error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "docker-registry.prelude.svc.cluster.local:5000/ce50113e09dc47ec90627aa66904dc5102f5d9f1cb167a94f1fcf292:latest": creating push check transport for docker-registry.prelude.svc.cluster.local:5000 failed: unrecognized HTTP status: 504 Gateway Time-out 

It looks like vra don't have access to ipam, but I got confirmation from network team that all network trafic is allow between vcsamgmt and phpIPAM. 

Any ideas? ;)

**Comment by vimwtf** [comment]
@musclar92 Hmm, that sounds to me like an error internal to vRA. You might see if [cleanly stopping and restarting the vRA components](https://docs.vmware.com/en/vRealize-Automation/8.2/Administering/GUID-99D06124-13F8-489A-B43C-EAEC3F4FE582.html#shut-down-vrealize-automation-0) helps to get things working again.

**Comment by ratheeshpc** [comment]
Any possibility to allocate MAC address, VLAN without IPAM in vRA8. 

Something like below in vRO7 

virtualMachineAddOrUpdateProperties = new Properties ();
virtualMachineAddOrUpdateProperties.put('Name', hostname);
virtualMachineAddOrUpdateProperties.put('VirtualMachine.Network0.MacAddressType', 'static');
virtualMachineAddOrUpdateProperties.put('VirtualMachine.Network0.MacAddress', mac);
virtualMachineAddOrUpdateProperties.put('VirtualMachine.Network0.Name', "VLAN"+vlan);

**Comment by vimwtf** [comment]
Hi @ratheeshpc,

Unfortunately I still haven't come across a way to do that, and I'm afraid I don't have much spare time at the moment to investigate it further. I hope you're able to find a solution though!

**Comment by ratheeshpc** [comment]
Hello @jbowdre ,

Thanks. I thought of placing question here as more members will be visiting this page. Thanks.

**Comment by kuklis** [comment]
Hi John,
another issue I have with (my implementation of) IPAM plugin is the following error message:
IP ALLOCATE failed: Failed to obtain auth credentials from /core/auth/credentials/1857dbd4-021b-4bea-8537-3168cc06c7ba: {'content': b'ClientResponse has erroneous status code: 404 Not Found

I found that the user token is expired and logout/login solves the problem, but it is annoying. Do you experience the same behavior and do you have any workaround? I was thinking about using a different method to fetch the endpoint credentials to avoid this issue. Or maybe this is fixed in a newer version of the SDK? I have not compared the changes in the last year...

**Comment by vimwtf** [comment]
Hi @kuklis,  

I've not encountered that myself, though [my solution](https://github.com/jbowdre/phpIPAM-for-vRA8/blob/main/src/main/python/allocate_ip/source.py#L101) is getting a fresh auth token for each run of the `allocate_ip` task. 

How/when/where are you doing the authentication in your integration?

**Comment by kuklis** [comment]
I do the same (I use PhpIpamClient), but mine fails at https://github.com/jbowdre/phpIPAM-for-vRA8/blob/main/src/main/python/commons/vra_ipam_utils/ipam.py#L330
This is a vRA token failure, not phpIPAM.

I think I'll download your version and see if I can reproduce the issue (I have a failing scenario). I'll get back to you with the results.

**Comment by vimwtf** [comment]
Oh that's really odd. Please do let me know how the testing goes.

**Comment by jedisamui** [comment]
Hey John, 

Thanks for the hardwork on this. Using your blog, I was able to get this up and running in my lab (vRA 8.7). 

Couple of things:
1) For the above "IP ALLOCATE failed: Failed to obtain auth credentials from" error, I get that from time to time. It's basically that your UI session has outlasted the phpIPAM token. Logging out of vRA and back in will reset it and all will be good. 

2) Have a scenario where I need to repurpose a hostname and IP address that has already been allocated and assigned via phpIPAM. However, if I attempt to manually assign the IP in the blueprint YAML, phpIPAM ignores that the IPAllocations array is already populated and will reassign a new IP using the next available IP Address. Is there a way to tell phpIPAM that I want to use a manually assigned IP address and to skip the allocation?

Thanks, 
Sam

**Comment by vimwtf** [comment]
Hi @jedisamui,

Thanks for the added insight on the auth credentials error. I suppose it might be possible to alter that VMware-provided code in [ipam.py](https://github.com/jbowdre/phpIPAM-for-vRA8/blob/main/src/main/python/commons/vra_ipam_utils/ipam.py) but I wouldn't know where to start on that.

For manually selecting an IP, you could probably pass that as a custom property from the blueprint YAML, and modify the [allocate_in_range](https://github.com/jbowdre/phpIPAM-for-vRA8/blob/main/src/main/python/allocate_ip/source.py#L142) function to insert that if specified. If the IP already exists in phpIPAM, you'd need to query the addresses controller to get the `id` associated with the IP, and then do a `PATCH` request to update it with the new details. 

That actually sounds like a fun exercise but I'm afraid I don't have time to dig into it right now.... it's been a crazy couple of weeks (and on that note, sorry for the slow reply!)

**Comment by chiencq** [comment]
Hi John,

I'm new member with vRA, I have a problem with phpIPAM integrated vRA that phpIPAM_GetIPRanges, phpIPAM_AllocateIP, phpIPAM_DeallocateIP failed. Only phpIPAM_ValidateEndpoint is OK. please help me.

**Comment by vimwtf** [comment]
Hi @chiencq,

That's not a lot of information to go on. It's also expected that the other actions will fail if `phpIPAM_Get_IPRanges` isn't working (since vRA won't have any knowledge about the available ranges). 

Are there any clues in the Action Runs logs on the vRA side? The Details of the `phpIPAM_GetIPRanges` run(s) should tell you what (if any) ranges were discovered and may shed light on what's not working.

**Comment by chiencq** [comment]
Hi John,

I installed phpIPAM, and config any VLAN as you. I dont follow from step 3 to end in your post. I downloaded phpIPAM plugin for vRA 8 at here: https://as.zabedu.ru/en/virtual2/vmware2/vrealize2/vra-phpipam-en

BUT, when i imported this plugin to vRA. phpIPAM_GetIPRanges, phpIPAM_AllocateIP, phpIPAM_DeallocateIP failed. Only phpIPAM_ValidateEndpoint is OK. I dont know why, and fix. 

When I downloaded this plugin, Do I have to edit that plugin?

**Comment by vimwtf** [comment]
The plugin that I wrote is available here:
https://github.com/jbowdre/phpIPAM-for-vRA8

I'm not going to be able to offer any help for someone else's code simply because I don't know how it works (and unfortunately don't currently have time to dig into it). 

I will again suggest looking at the extensibility action run logs though. Those should provide clues for where the process is failing. 

I wish you luck in your investigation!

**Comment by chiencq** [comment]
Hi John, 
Thanks for your support. but I have a question that: 
I'm using vRA 8.4, so can I use your plugin? And do I need to edit your plugin to be compatible with my vRA environment? sorry about this, because i don't know about code.

**Comment by vimwtf** [comment]
@chiencq I originally wrote this integration against vRA 8.2. I've updated it a few times along the way to make sure it would keep working with newer releases. I *think* it should still work against those older releases too, but I don't have an 8.4 environment to test it against anymore.

You shouldn't need to modify the package; just download the release and import that into vRA as described in the repo.

**Comment by chiencq** [comment]
Hi John,
Thanks so much, I will try on Monday in next week.

**Comment by chiencq** [comment]
Hi John,

I integrated your plugin to my vRA 8.4, but i have three problems: 
 1. In Network profile > Network tab, click one Network:
     If I left the Domain field blank, the problem occurs as follows:
        - With Linux: Can not deployment
        - Windows is OK
     If I fill Domain, ex: org.local
        - With Linux: OK
        - Windows: Can not depoyment, error msg: "customization operation failed error from vcenter spec.identification.domainAdmin"
2. IP can not assign in VM and vcenter, in phpipam still IP asigned to VM
 
Please help me. Thank so much.

**Comment by vimwtf** [comment]
Do the `phpIPAM_*` actions complete successfully or do they log errors when retrieving the list of IP ranges or allocating an IP?

The integration doesn't do anything to distinguish between Windows and Linux VMs, but the "customization operation failed" message makes it sound like there may be something wrong with either your cloud template(s) or vCenter customization specs.

**Comment by chiencq** [comment]
Hi John,

phpIPAM_GetIPRanges, phpIPAM_AllocateIP, phpIPAM_DeallocateIP phpIPAM_ValidateEndpoint is OK. Only phpIPAM_update failed.

in the phpIPAM, i still IP assigned to VM, but in vCenter or VM not assigned.

about customization spec: what can i do now? during install cloudbase init, i checkbox Sysprep and shutdown at Finish screen. 
please help me.

**Comment by vimwtf** [comment]
Okay so that does sound like the integration is working correctly and the disconnect is somewhere else. Fixing the clout template / customization spec is a bit broader topic, and it may be highly dependent upon your environment. 

For Windows, I've got some notes on how to match things up in my other vRA articles, starting with this one:
https://www.virtuallypotato.com/vra8-custom-provisioning-part-one/

I haven't documented my approach to Linux builds yet (and frankly probably won't, as I'm pivoting most of my provisioning efforts to Terraform now).

Best of luck, but I'm not going to be able to help you further.
