### ISSUE TITLE
Cloud-hosted WireGuard VPN for remote homelab access - Virtually Potato

### ISSUE THREAD

**Issue by utterances-bot** [vimwtf/site-comments#17]
# Cloud-hosted WireGuard VPN for remote homelab access - Virtually Potato

For a while now, I've been using an OpenVPN Access Server virtual appliance for remotely accessing my homelab. That's worked fine but it comes with a lot of …

[https://www.virtuallypotato.com/cloud-based-wireguard-vpn-remote-homelab-access/](https://www.virtuallypotato.com/cloud-based-wireguard-vpn-remote-homelab-access/)

**Comment by hatcreek68** [comment]
Ran into an issue starting wireguard (systemctl start wg-quick@wg0
) it threw an error b/c I had not spec'd out the private key yet, having just left PrivateKey = {GCP_PRIVATE_KEY}, which seems to be the root cause behind the error.  Can you expand on the the details on how you obtain the key from your wg genkey command into the .conf file; from what I understand we makes key files into the wireguard directory but then what?  For the time being i put a dummy key in the .conf to just get it to load/start.... or is PrivateKey = {GCP_PRIVATE_KEY}
supposed to reference the key as a variable in the other file... if so it didn't seem to work. Thanks - Linux novice.

**Comment by vimwtf** [comment]
Hi @hatcreek68!

Sorry, it looks like my instructions may not have been as clear as I thought they were.

You'll use the command `wg genkey | tee client.key | wg pubkey > client.pub` for generating the key pair for each Wireguard peer. So run that on the instance in GCP to generate its key pair, run it on a VM in your homelab to generate its key pair, and run it on your Linux laptop to generate its keypair. 

The Wireguard configuration file on each peer needs to know its own _private_ key as well as the _public_ key of all the other peers. So given the command that I mentioned above, you'd copy the contents of the `client.key` file into the `PrivateKey` field of the config - and you'd copy the contents of the `client.pub` file into the `PublicKey` field of the `[Peer]` section on all the other peers.

Does that help to make it a little clearer?

Alternatively, if you'd like the security, performance, and flexibility of Wireguard without having to manually create configs and keypairs, you might want to check out [Tailscale](https://tailscale.com/). I've since moved from the Wireguard setup that I described in this post to a new one built around Tailscale and I'm much happier: https://www.virtuallypotato.com/secure-networking-made-simple-with-tailscale/

**Comment by hatcreek68** [comment]
Awesome. Between your answer and reviewing other folk's setups its more clear now (someone mentioned using CAT to read back the keys and copy/paste to the .conf) - thank you! 

Blabbing on - I got the GCP-instance to connect to my pi but was going to have to setup nginx and routings..... and starting questioning why I actually need remote access to my  LAN, which was mostly just being annoyed at not being able to get an HTTPS cert behind CGNAT, at least not w/ DDNS and port forwarding as i had done in the past.  At any rate- Tailscale looks really promising thanks for the tip!  I'm curious to see if i can setup remote access to my LAN w/ tailscale which I can somehow control remotely as well so remote access isn't always 'on'.   Perhaps you could do that by flipping a switch on the tailscale server... i'll eventually dig into it!

**Comment by vimwtf** [comment]
@hatcreek68 Awesome, I'm glad you were able to make some headway!

The whole reason that I went with the cloud-hosted solution as described in this article was so that I could have remote access to my home network _without_ having to do any routing/firewall/port-forwarding shenanigans. The on-premise peer is able to send a keep-alive to the GCP peer, and then the GCP peer can always know how to get back in. 

Tailscale takes that [a bit further with their DERPS](https://tailscale.com/blog/how-tailscale-works/) so I don't need my own cloud server to maintain the persistent NAT session; additionally I can install the Tailscale client on my other cloud servers so I can SSH to them without needing port 22 to be exposed to the internet at all. 

On that note, there's not really any reason to _not_ have the remote access be always on (with either vanilla Wireguard or with the Tailscale control plane added in). Nothing is getting exposed or advertised, nor is there anything really listening for a login or just waiting to get brute-forced. Back in the olden days when I was using OpenVPN as my remote access solution, having it always-on was definitely a concern to me. Anyone could hit the HTTPS port on my router, get forwarded to my OpenVPN virtual appliance, and try their darndest to log in (at least until `fail2ban` kicked in and blocked them). I don't have to worry about that with Wireguard/Tailscale. 

It's definitely a more modern way to handle remote access (specifically) and zero-trust networking at large.
