### ISSUE TITLE
BitWarden password manager self-hosted on free Google Cloud instance - Virtually Potato

### ISSUE THREAD

**Issue by utterances-bot** [vimwtf/site-comments#18]
# BitWarden password manager self-hosted on free Google Cloud instance - Virtually Potato

A friend mentioned the BitWarden password manager to me yesterday and I had to confess that I'd never heard of it. I started researching it and was impressed by …

[https://www.virtuallypotato.com/bitwarden-password-manager-self-hosted-on-free-google-cloud-instance/](https://www.virtuallypotato.com/bitwarden-password-manager-self-hosted-on-free-google-cloud-instance/)

**Comment by CatatonicBug** [comment]
It appears that the reference to mprasil/bitwarden is no longer valid. I admit that I am essentially flying blind, just copy/pasting to get this all to work, but the command you have to install bitwarden_rs does not work, saying that the manifest for mprasil/bitwarden is unknown. Can you suggest an alternative?

**Comment by vimwtf** [comment]
Hi @CatatonicBug,

In the years since I wrote the post it looks like the project was renamed to `vaultwarden`:

https://github.com/dani-garcia/vaultwarden

Hopefully you should be able to replace references to `mprasil/bitwarden_rs` with `vaultwarden/server` based on the instructions there. 

Please let me know how it goes and I'll try to update the post.

**Comment by CatatonicBug** [comment]
I was able to change references to "mprasil/bitwarden" to "vaultwarden/server". I also had to ignore the first half of your Certbot instructions, but since you linked to the certbot website, I was able to follow the instructions they have posted, including installing snapd. I got so tied up in their instructions that I used their tool to deploy the certs too, and that ended up tying up port 443 on my server, making the whole project fail. Once I realized your instruction to run the "standalone" command and copy/paste the certs, I re-ran the project and I now have a fully operational google cloud instance of Bitwarden! Not only is this my first cloud-based, self-managed project, but it's done in linux (debian), which is foreign to me. All thanks to your instructions!

**Comment by vimwtf** [comment]
@CatatonicBug Awesome, I'm very glad to hear that you got it working! And, if you're anything like me, I'm sure that you learned a ton in the process since you had to make a few changes along the way due to my outdated instructions. That's the real win.

In any case, I did go back and update the post to account for the project name change, and I tweaked the `certbot` install instructions since it should be available in the default apt repositories on more recent Debian systems. (I don't typically use a lot of Snap packages primarily because I like having a single command for updating all the packages on a system, but I do appreciate the appeal of Snaps from a developer perspective.)

In any case, thanks for reminding me that this post needed upating, and for letting me know that your project was successful. Congratulations on getting through it!
