### ISSUE TITLE
Automatic unattended expansion of Linux root LVM volume to fill disk - Virtually Potato

### ISSUE THREAD

**Issue by utterances-bot** [vimwtf/site-comments#19]
# Automatic unattended expansion of Linux root LVM volume to fill disk - Virtually Potato

While working on my vRealize Automation 8 project, I wanted to let users specify how large a VM's system drive should be and have vRA apply that without any …

[https://www.virtuallypotato.com/automatic-unattended-expansion-of-linux-root-lvm-volume-to-fill-disk/](https://www.virtuallypotato.com/automatic-unattended-expansion-of-linux-root-lvm-volume-to-fill-disk/)

**Comment by perpi** [comment]
Why 'ext2' in lines 14 and 17?

**Comment by perpi** [comment]
VMWare vCenter Menu > Policies and Profiles > VM Customization > New > Linux > Customization Script: "The script cannot exceed 1500 characters."

Your script has more the 3000 characters )':

**Comment by vimwtf** [comment]
> Why 'ext2' in lines 14 and 17?

Just to give `parted` a partition type so that it will run the command without throwing any errors. The label here doesn't really matter since the partition gets LVM'd and then the existing file system (whatever format it is) gets extended atop that.

> VMWare vCenter Menu > Policies and Profiles > VM Customization > New > Linux > Customization Script: "The script cannot exceed 1500 characters."
> 
> Your script has more the 3000 characters )':

Interesting. I wrote this for deployment with vRA rather than direct application within vCenter customization scripts so I've never tested that usage. Would it be possible to stage the script on your VM template and just include a call to it from the vCenter customization script?

**Comment by perpi** [comment]
Thanks for your prompt reply; The code does not work on fresh Ubuntu with sda1 (1M), sda2 (1G, boot), and sda3 (/, LVM);
- Err1: https://p.teknik.io/qz23m
- After removing lines 55 and 59, Err2: https://p.teknik.io/UvKwv (running the script in debug mode: https://p.teknik.io/Ns7x0)

\+ In line 42, `diskshort` appears unused.

**Comment by vimwtf** [comment]
Thanks for raising this; I definitely should have mentioned in the post that I was primarily targeting Enterprise Linux derivatives (RHEL, CentOS) with this script. I didn't do any testing of it against Ubuntu. 

It looks like it would need to be modified to account for the use of GPT versus MBR, and I'm afraid I don't have the free cycles at the moment to devote to that. I'd love to see what you come up with if you're able to get it working though!
