### ISSUE TITLE
Setting up Linux on a new Lenovo Chromebook Duet (bonus arm64 complications!) - Virtually Potato

### ISSUE THREAD

**Issue by utterances-bot** [vimwtf/site-comments#5]
# Setting up Linux on a new Lenovo Chromebook Duet (bonus arm64 complications!) - Virtually Potato

I’ve written in the past about the Linux setup I’ve been using on my Pixel Slate. My Slate’s keyboard stopped working over the weekend, though, and there don’t seem to be any replacements (either Google or Brydge) to be found. And then I saw that Walmart had the 64GB Lenovo Chromebook Duet temporarily marked down to a mere $200 - just slightly more than the Slate’s keyboard originally cost. So I jumped on that deal, and the little Chromeblet showed up today.

[https://virtuallypotato.com/setting-up-linux-on-a-new-lenovo-chromebook-duet-bonus-arm64-complications](https://virtuallypotato.com/setting-up-linux-on-a-new-lenovo-chromebook-duet-bonus-arm64-complications)

**Comment by vimwtf** [comment]
**Ruud van der Ham**
*Posted March 19, 2021 on [Hashnode](https://hash.virtuallypotato.com/setting-up-linux-on-a-new-lenovo-chromebook-duet-bonus-arm64-complications#ckmfx2vku04an9js14r4u5o3b)*

I was wondering whether there's an on-screen keyboard available when there's no keyboard connected (in tablet mode). If so, does that work adequately?

**Comment by vimwtf** [comment]
**John Bowdre**
*Posted March 19, 2021 on [Hashnode](https://hash.virtuallypotato.com/setting-up-linux-on-a-new-lenovo-chromebook-duet-bonus-arm64-complications#ckmgbpkfc012563s1fj88bj04)*

Chrome OS does have an on-screen keyboard, and you can also use gBoard if you wish. I don't think those options work great for the Linux terminal, but they'll do in a pinch - and they're perfectly adequate for standard web browsing and such.

**Comment by vimwtf** [comment]
**Austin Thomas**
*Posted May 20, 2021 on [Hashnode](https://hash.virtuallypotato.com/setting-up-linux-on-a-new-lenovo-chromebook-duet-bonus-arm64-complications#ckoxnh8kf02n8eks19nna3h07)*

Hey, John:

This is a great post and I was very excited to find it. I have a Lenovo Duet myself, and wanted to get Powershell setup. All the steps seem to go ok, but when I type PWSH, it tells me that the command is invalid or not found. Any idea where I'm going wrong? I've actually destroyed the linux VM and recreated on my Chromebook twice, stepping through these steps, and I just can't get it to work. Any input would be greatly appreciated.

**Comment by vimwtf** [comment]
**John Bowdre**
*Posted May 20, 2021 on [Hashnode](https://hash.virtuallypotato.com/setting-up-linux-on-a-new-lenovo-chromebook-duet-bonus-arm64-complications#ckoxp4v1k02vreks1e2huei6a)*

Hi Austin!

Sorry to hear you ran into trouble. I was a little afraid that my PowerShell instructions wouldn't be "good" for very long since (at the time) arm64 didn't appear to be officially supported. It's actually great that you brought this to my attention - I was working the other day and VS Code started nagging me about needing to update PowerShell and I wasn't completely sure how I was going to do it.

The good news is that arm64 now does seem to be [officially supported](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#support-for-arm-processors), but we still have to manually install the binaries since there still isn't a nice `.deb` package. I actually just nuked my previous PowerShell installation and installed the [newer version](https://github.com/PowerShell/PowerShell/releases/tag/v7.2.0-preview.5) using [Microsoft's instructions](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#linux).

```shell
❯ curl -L -o /tmp/powershell.tar.gz https://github.com/PowerShell/PowerShell/releases/download/v7.2.0-preview.5/powershell-7.2.0-preview.5-linux-arm64.tar.gz
❯ sudo mkdir -p /opt/microsoft/powershell/7
❯ sudo tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7
❯ sudo chmod +x /opt/microsoft/powershell/7/pwsh
❯ sudo ln -s /opt/microsoft/powershell/7/pwsh /usr/bin/pwsh

❯ pwsh
PowerShell 7.2.0-preview.5
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /home/jbowdre>
```

(And I have no clue if comments here support markdown so apologies if the formatting is screwy! I'll update the post with these newer slightly-different instructions too.)

Hopefully that helps get you up and running!

**Comment by fjaym** [comment]
Any chance of dechroming the duet entirely rather than just using the VM?

**Comment by vimwtf** [comment]
> Any chance of dechroming the duet entirely rather than just using the VM?

Putting a Chromebook into Developer Mode would let you run Linux stuff in a [chroot environment](https://github.com/dnschneid/crouton) or even [dual-boot a different OS](https://galliumos.org/) if you'd prefer, though it also defeats Chrome OS security and makes it all too easy to completely brick the device if you don't know exactly what you're doing. 

Personally I really appreciate the security, convenience, and stability of Chrome OS, and being able to use Linux tools without compromising any of that is just about perfect for my needs.
